---
- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - { role: bastion-base }
    - { role: sftd, scaleft_platform_url: "{{ scaleft_platform_url }}", scaleft_pkg_url: "{{ scaleft_pkg_url }}"}
